# Vivado Tcl Script to Recreate the Q-OS Hardware Project

# 1. Set Project Name and Directory
set project_name "q_os_fpga"
set output_dir "build_vivado"
file mkdir $output_dir

# 2. Create Project
# Change "xc7z020clg400-2" to your specific Alinx FPGA part number
create_project $project_name $output_dir -part xc7z020clg400-2 -force

# 3. Add Design Sources
add_files hardware/hdl/q_os_mimetic_top.v
add_files hardware/hdl/sphy_wave_gen.v
add_files hardware/hdl/sphy_spi_transceiver.v
# Add the memory file generated by Python
add_files sphy_table.mem

# 4. Add Constraints
add_files -fileset constrs_1 hardware/constraints/q_os.xdc

# 5. Set Top Module
set_property top q_os_mimetic_top [current_fileset]

# 6. Run Synthesis
puts "Starting Synthesis..."
launch_runs synth_1 -jobs 4
wait_on_run synth_1

# Check for Synthesis errors
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    puts "ERROR: Synthesis failed"
    exit 1
}

# 7. Run Implementation
puts "Starting Implementation..."
launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1

# Check for Implementation errors
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    puts "ERROR: Implementation failed"
    exit 1
}

puts "Bitstream generated successfully!"
puts "Location: [get_property DIRECTORY [get_runs impl_1]]/${project_name}.bit"